server:
  port: 8182
  servlet:
    context-path: /codecurious
spring:
  application:
    name: code curious application
  profiles:
    active: prod







springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /document

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true


##-----
##dev

##--
##prod


