spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=codeCuriousDB
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: code@curious#123!
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.SQLServerDialect
      hibernate:
        ddl-auto: create